%{
/* Part 1: Lexer for Project Part 3 
   Updates: Populates yystype (yylval) instead of creating Tree Nodes.
*/
#include <string>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include "part3_helpers.hpp" 
#include "part3.tab.hpp"      /* Generated by Bison */

using namespace std;

int line_number = 1;

/* Helper to fill the struct fields easily */
void initNode(string name) {
    yylval.name = name;
    // Vectors like nextList/trueList are empty by default in the struct constructor
}
%}

%option noyywrap

integernum  [0-9]+
realnum     [0-9]+\.[0-9]+
id          [a-zA-Z][a-zA-Z0-9_]*
str         \"([^"\\]|\\n|\\t|\\r|\\\\|\\\")*\"
whitespace  [ \t]+

%%

[\n]          { line_number++; }
[\r]          { /* ignore */ }
{whitespace}    { /* Ignore whitespace */ }
"#"[^\r\n]* { /* Ignore comments */ }

"int"           { initNode("int"); return INT; }
"float"         { initNode("float"); return FLOAT; }
"void"          { initNode("void"); return VOID; }
"write"         { initNode("write"); return WRITE; }
"read"          { initNode("read"); return READ; }
"while"         { initNode("while"); return WHILE; }
"do"            { initNode("do"); return DO; }
"if"            { initNode("if"); return IF; }
"then"          { initNode("then"); return THEN; }
"else"          { initNode("else"); return ELSE; }
"return"        { initNode("return"); return RETURN; }

"("             { initNode("("); return LPAREN; }
")"             { initNode(")"); return RPAREN; }
"{"             { initNode("{"); return LCURLY; }
"}"             { initNode("}"); return RCURLY; }
","             { initNode(","); return COMMA; }
";"             { initNode(";"); return SEMICOLON; }
":"             { initNode(":"); return COLON; }

{integernum}    { initNode(yytext); return INTEGERNUM; }
{realnum}       { initNode(yytext); return REALNUM; }
{id}            { initNode(yytext); return ID; }

{str}           { 
                  // Strip quotes from string
                  string s = yytext;
                  if(s.length() >= 2) s = s.substr(1, s.length()-2);
                  initNode(s); 
                  return STR; 
                }

"=="|"<>"|"<="|">="|"<"|">" { initNode(yytext); return RELOP; }
"="             { initNode("="); return ASSIGN; }
"+"|"-"         { initNode(yytext); return ADDOP; }
"//"            { 
                  cerr << "Lexical error: '//' in line number " << line_number << endl;
                  exit(LEXICAL_ERROR); 
                }
"*"|"/"         { initNode(yytext); return MULOP; }
"&&"            { initNode("&&"); return AND; }
"||"            { initNode("||"); return OR; }
"!"             { initNode("!"); return NOT; }

.               { 
                  cerr << "Lexical error: '" << yytext << "' in line number " << line_number << endl;
                  exit(LEXICAL_ERROR); 
                }

%%